[versions]
hoplite = "2.3.3"
kotlin = "1.7.10"

[libraries]
hopliteCore = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite" }
hopliteHocon = { module = "com.sksamuel.hoplite:hoplite-hocon", version.ref = "hoplite" }
hopliteJson = { module = "com.sksamuel.hoplite:hoplite-json", version.ref = "hoplite" }
hopliteToml = { module = "com.sksamuel.hoplite:hoplite-toml", version.ref = "hoplite" }
hopliteYaml = { module = "com.sksamuel.hoplite:hoplite-yaml", version.ref = "hoplite" }

[bundles]
hoplite = [ "hopliteCore", "hopliteHocon", "hopliteJson", "hopliteToml", "hopliteYaml" ]

[plugins]
kotlinGradlePlugin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinBinaryCompatibilityPlugin = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.11.0" }
mavenPublishGradlePlugin = { id = "maven-publish", version = "0.18.0" }
protobufGradlePlugin = { id = "com.google.protobuf", version = "0.8.19" }