[versions]
kotest = "5.3.2"

[libraries]
assertj = "org.assertj:assertj-core:3.23.1"
kotestAssertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotestJunitRunnerJvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotestProperty = { module = "io.kotest:kotest-property", version.ref = "kotest" }

[bundles]
kotest = [ "kotestAssertions", "kotestJunitRunnerJvm", "kotestProperty" ]

[plugins]
